services:
  traefik:
    image: traefik:3.5
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    command:
      - --api.dashboard
      - --providers.swarm
      - --providers.swarm.network=traefik
      - --providers.swarm.exposedByDefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: proxy
        traefik.http.routers.api.entrypoints: web
        traefik.http.routers.api.service: api@internal 
        traefik.http.routers.api.rule: Host(`dashboard.raspi.internal`)
        traefik.http.services.grafana.loadbalancer.server.port: "80"

networks:
  proxy:
    name: proxy
    driver: overlay
