global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: node_exporter
    static_configs:
      - targets:
        - host.docker.internal:9100

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
    metric_relabel_configs:
      - regex: id
        action: labeldrop
      - regex: container_label_com_docker_swarm_(service_name|task_id|task_name)
        action: labeldrop
      - regex: container_label_maintainer
        action: labeldrop
      - source_labels:
          - __name__
        regex: container_tasks_state
        action: drop
      - source_labels:
          - __name__
        regex: container_memory_failures_total
        action: drop

  - job_name: snmp_ix2215
    static_configs:
      - targets:
          - 192.168.1.254
    metrics_path: /snmp
    params:
      module:
        - if_mib
        - nec_ix
    relabel_configs:
      - source_labels:
        - __address__
        target_label: __param_target
      - source_labels:
        - __param_target
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
